import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import {useJoinLobby} from "../utils/events";
import {useState} from "react";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  const [players, setPlayers] = useState<string[]>([])
  useJoinLobby((playerName) => setPlayers([...players, playerName]))

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
        {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading...</p>}
      </div>
      <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
        {players ? <ul>{players.map((player, i) => <li key={i}>{player}</li>)}</ul> : <p>No Players Yet...</p>}
      </div>
    </>
  );
};

export default Home;
