import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import { useCookies } from "react-cookie";
import { useRef } from "react";
import Image from "next/image";

const Home: NextPage = () => {
  const router = useRouter();

  const createLobby = trpc.useMutation("lobby.create", {
    onSuccess: (data) => {
      router.push(`/lobby/${data.lobbyCode}`);
    },
  }).mutate;

  const joinLobby = trpc.useMutation("lobby.join", {
    onSuccess: (data) => {
      router.push(`/lobby/${data.lobbyCode}`);
    },
  }).mutate;

  const joinElement = useRef<HTMLInputElement>(null);
  const [cookies, setCookie] = useCookies(["name"]);

  return (
    <>
      <Head>
        <title>woodvale</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid h-screen place-items-center">
        <p className="text-4xl font-extrabold font-mono text-center">
          Welcome to Sana&apos;s Swiftie Game hub
        </p>
        <p className="text-lg italic text-center">let the games begin...</p>
        <Image
          className="mask mask-squircle float-left"
          src="/homepage.jpeg"
          alt="TS 1989"
          width={650}
          height={430}
        />
        <div>
          <input
            type="text"
            value={cookies.name}
            onChange={(e) => setCookie("name", e.target.value)}
            placeholder={"Type name"}
            className="input input-bordered w-full max-w-xs"
          />

          <div className="btn-group">
            <button
              className="btn btn-primary"
              onClick={() => {
                createLobby();
              }}>
              Create
            </button>
            <button
              className="btn"
              onClick={() => {
                if (!joinElement.current?.value) {
                  return;
                }
                joinLobby({
                  lobbyCode: joinElement.current.value,
                });
              }}>
              Join
            </button>
          </div>
          <input
            ref={joinElement}
            type="text"
            placeholder={"Join lobby code"}
            className="input input-bordered w-full max-w-xs"
          />
        </div>
      </div>
    </>
  );
};

export default Home;
